spring.application.name=currency-conversions
server.port=8084
spring.config.import=optional:configserver:http://localhost:8888

# Configuration for MySQL Database
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url = jdbc:mysql://localhost:3306/mustafeez
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql:true

#Eureka server registry
eureka.client.service-url.defaultZone=http://localhost:8761/eureka


#Circuit breaker / resilience
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=50
resilience4j.circuitbreaker.configs.default.sliding-window-size=10

#Retry property
resilience4j.retry.instances.conversion-service.max-attempts=3
resilience4j.retry.instances.conversion-service.wait-duration=20s
#resilience4j.retry.instances.conversion-service.enable-exponential-backoff=false